### ISSUE TITLE
Getting NPE when run the forget-me.sh

### ISSUE THREAD

**Issue by chaminda** [wso2/product-das#290]
**Description:**
Getting below NPE when user runs forget-me.sh as below.
>forget-me.sh -U <userName>

```java
2018-03-08 17:52:36 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 0d7da493-a963-4e17-aed6-1542e94b433f
Exception in thread "main" java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstructionReader.loadStreamDefinitions(AnalyticsStreamsInstructionReader.java:91)
	at org.wso2.carbon.privacy.forgetme.analytics.streams.instructions.AnalyticsStreamsInstructionReader.read(AnalyticsStreamsInstructionReader.java:72)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.getInstructions(ForgetMeExecutionEngine.java:143)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.startExecutors(ForgetMeExecutionEngine.java:121)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:90)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)

```

**Affeced Product Version:**
wso2das-3.2.0-alpha

**OS, DB, other environment details and versions:**    
macOs High Sierra, jdk1.8.0_152, H2

**Steps to reproduce:**
1. Add stream, even receiver(http), and publisher(logger)
2. Send several events with users PII data.
3. Configure config.json and streams.json as below
4. Run forget-me.sh by providing the user name.

Streams.json
```json
{
    "streams": [
        {
            "streamName": "com.wso2.streams.teststream",
            "attributes": ["name", "age"],
            "id": "id"
        }
    ]
}
```

config.json
```json
{
  "processors" : [
    "log-file",
    "analytics-streams"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "/Users/cjayawardena/Documents/Testing/DAS/wso2das-3.2.0-alpha/repository/logs",
      "log-file-name-regex" : "(.)*"
    },
    {
      "dir": "/Users/cjayawardena/Documents/Testing/DAS/wso2das-3.2.0-alpha/repository/deployment/server/eventstreams",
      "type": "analytics-streams",
      "processor" : "analytics-streams"
    }
  ]
}
```

**Comment by pcnfernando** [comment]
Issue was with the configurations in config.json. "dir" parameter should point to the Streams.json directory. By default the sample Streams.json exists within "streams" directory.  Relative path from  <DAS_HOME>/repository/components/tools/identity-anonymization-tool-x.x.x/conf directory should be provided as the "dir" parameter.

**Comment by chaminda** [comment]
The information is missing in the document so added #305 to track this
